# Generated by Django 3.2 on 2023-08-07 19:39

from django.db import migrations


def load_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(name=flat.owner, phonenumber=flat.owners_phonenumber,
                                                    pure_phone=flat.owner_pure_phone
                                                    )
        owner.flats.set([flat])
        owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230807_2232'),
    ]

    operations = [
        migrations.RunPython(load_flats)
    ]
